services:
  MailGenerator-client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
      args:
        VITE_API_URL: ${SERVER_URL}
    container_name: mailgenerator-client
    image: mailgenerator-client
    environment:
      - VITE_API_URL=${SERVER_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.MailGenerator-client.rule=Host(`${CLIENT_DOMAIN}`)"
      - "traefik.http.routers.MailGenerator-client.entrypoints=websecure"
      - "traefik.http.routers.MailGenerator-client.tls.certresolver=myresolver"
    depends_on:
      - MailGenerator-server

  MailGenerator-server:
    build: ./server
    container_name: mailgenerator-server
    image: mailgenerator-server
    volumes:
      - ./server:/app
      - /app/node_modules
      - mailgenerator-uploads:/app/uploads
      - mailgenerator-data:/app/data
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - CLIENT_URL=${CLIENT_URL}
      - SERVER_PORT=${SERVER_PORT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.MailGenerator-server.rule=Host(`${SERVER_DOMAIN}`)"
      - "traefik.http.services.MailGenerator-server.loadbalancer.server.port=${SERVER_PORT}"
      - "traefik.http.services.MailGenerator-server.loadbalancer.server.scheme=http"
      - "traefik.http.routers.MailGenerator-server.entrypoints=websecure"
      - "traefik.http.routers.MailGenerator-server.tls.certresolver=myresolver"
