services:
  MailGenerator-client:
    build: ./client
    container_name: mailgenerator-client
    image: mailgenerator-client
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=${SERVER_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.MailGenerator-client.rule=Host(`${CLIENT_URL}`)"
      - "traefik.http.routers.MailGenerator-client.entrypoints=websecure"
      - "traefik.http.routers.MailGenerator-client.tls.certresolver=myresolver"
    depends_on:
      - MailGenerator-server

  MailGenerator-server:
    build: ./server
    container_name: mailgenerator-server
    image: mailgenerator-server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - CLIENT_URL=${VITE_CLIENT_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.MailGenerator-server.rule=Host(`${SERVER_URL}`)"
      - "traefik.http.services.MailGenerator-server.loadbalancer.server.port=${SERVER_PORT}"
      - "traefik.http.routers.MailGenerator-server.entrypoints=websecure"
      - "traefik.http.routers.MailGenerator-server.tls.certresolver=myresolver"
