# Dockerfile.prod pour MailGenerator-server
FROM node:18

WORKDIR /app

COPY package*.json ./
RUN npm install --production

COPY . .

ARG CLIENT_URL
ARG SERVER_PORT
ENV CLIENT_URL=$CLIENT_URL
ENV SERVER_PORT=$SERVER_PORT

ENV NODE_ENV=production

CMD ["node", "index.js"]